### ISSUE TITLE
Validate based on repository name

### ISSUE THREAD

**Issue by miracle2k** [flynn-archive/gitreceived#13]
I'm not sure about the security implications of moving the auth-check script to after the connection has already been accepted; probably not a good idea.

A third "check repo" phase seems like considerable complexity.

Maybe the receiver binary should be allowed to return an error code; that means a wasteful "git archive", but it might be the least bad option.

**Comment by progrium** [comment]
Hmm... if you have time, try prototyping the combination of
https://github.com/progrium/execd and https://github.com/progrium/gitreceive
to acheive a slightly more expressive version of gitreceived. It would let
you do this without hitting `git archive`. It's on my list, but it's not a
priority yet.

On Thu, Jun 19, 2014 at 5:23 AM, Michael Elsdörfer <notifications@github.com

> wrote:
> 
> I'm not sure about the security implications of moving the auth-check
> script to after the connection has already been accepted; maybe not a good
> idea.
> 
> A third "check repo" phase seems like considerable complexity.
> 
> Maybe the receiver binary should be allowed to return an error code; that
> means a wasteful "git archive", but it might be the least bad option.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/flynn/gitreceived/issues/13.

## 

Jeff Lindsay
http://progrium.com

**Comment by titanous** [comment]
We had the auth check after the connection was accepted previously, but had to change it so that clients that present multiple keys could connect successfully: 4d95f839762848537dfd00225c39cd6475a9a0b9
