### ISSUE TITLE
Comparison to Gandalf

### ISSUE THREAD

**Issue by enyachoke** [flynn-archive/gitreceived#2]
This is a just out of curiosity and maybe not a real issue  how does gitreceive-next compare with https://github.com/globocom/gandalf which provides an easy and straight forward management of git repos,users,ssh keys and access control over a rest api. And can this be replaced with gandalf.

**Comment by progrium** [comment]
Gitreceive is in a way more specific and more general. It doesn't let you
manage repositories, it lets you handle pushes. It might become even more
general soon as noted in the readme.

These shouldn't be filed as issues.

On Monday, November 18, 2013, Emmanuel Nyachoke wrote:

> This is a just out of curiosity and maybe not a real issue how does
> gitreceive-next compare with https://github.com/globocom/gandalf which
> provides an easy and straight forward management of git repos,users,ssh
> keys and access control over a rest api. And can this be replaced with
> gandalf.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/flynn/gitreceive-next/issues/2
> .

## 

Jeff Lindsay
http://progrium.com
