### ISSUE TITLE
Crash during push didn't result in push rejection

### ISSUE THREAD

**Issue by Qard** [flynn-archive/gitreceived#5]
With heroku, you can force push, which is handy for blowing away incomplete deploys. I had shelf misconfigured so I tried to redeploy, but I had to make a new commit before I was able to push again.

**Comment by titanous** [comment]
Hmm, was there an error when you force-pushed? It is definitely a bug if that doesn't work.

**Comment by Qard** [comment]
No error. Just says nothing has changed.

**Comment by lmars** [comment]
@Qard are you trying to force push the branch even though it hasn't moved? If the original deploy was unsuccessful, was the push not rejected?

**Comment by Qard** [comment]
The original push crashed because there was no shelf. When I tried to push
again, after fixing the shelf, it gave the standard git message that
everything was up-to-date.

**Comment by titanous** [comment]
It sounds like the receive wasn't rejected when it crashed, which is why a subsequent push didn't do anything.
