### ISSUE TITLE
git push flynn master doesn't use added ssh keys

### ISSUE THREAD

**Issue by dstaley** [flynn-archive/gitreceived#7]
After adding `keyA_rsa.pub`, `keyB_rsa.pub`, and `keyC_rsa.pub` (all of my public keys) with `flynn key-add`, `git push flynn master` still returns an error.

[`ssh -v git@GITHOST` output](https://gist.github.com/dstaley/d1687391cdc6aadc00fe)

However, after creating `id_rsa.pub` and adding it, `git push flynn master` works.

**Comment by titanous** [comment]
@dstaley I pushed a new version of flynn/gitreceive that checks keys properly, would you try it out?

**Comment by dstaley** [comment]
LGTM :+1:
