### ISSUE TITLE
Build without `index out of bounds` error when executing result

### ISSUE THREAD

**Issue by davidpelaez** [flynn-archive/gitreceived#8]
Hi,

I'm trying to build the code with something similar to what appears here in the makefile https://github.com/flynn/flynn-receive/blob/master/Makefile

I basically install mercural, set GOPATH to my home, run build through godeps and it compiled and all but when running the actual binary I get this:

```
panic: runtime error: index out of range

goroutine 1 [running]:
runtime.panic(0x5ace20, 0x7ed877)
    /usr/lib64/golang/src/pkg/runtime/panic.c:266 +0xb6
main.main()
    /home/fedora/tmp/gitreceived/gitreceived.go:65 +0xdde
```

I tried in several different environments (Fedora, Ubuntu) and I don't know what I'm missing.

Thanks.

**Comment by titanous** [comment]
It's crashing because there are mandatory arguments but no bounds check+error if they are not provided, the workaround is to provide the correct number of arguments (they are documented in the README). Are you interested in fixing it? If not, I'll go ahead and do it.

**Comment by davidpelaez** [comment]
Hmmm. I can take a look, but I have no idea how. It'd be more like read and understand thing. If it's very fast then please go ahead and fix it if possible, otherwise let me know and I'll try to fixt it tonight with the info you gave.

**Comment by davidpelaez** [comment]
That was quick, thanks. The conditional comparison number had to be increased by 1 to take into account the case where 1 of the 3 required params was missing. Minor change suggested here: https://github.com/flynn/gitreceived/pull/9
